version: '3'

services:
 minio1:
  image: minio/minio
  # hostname: minio1
  hostname: "{{.Service.Name}}-{{.Task.Slot}}"
  volumes:
   - dirac_storage1:/export
  ports:
   - "9001:9000"
  networks:
    - dirac_distributed
  environment:
   MINIO_ACCESS_KEY: nlesc
   MINIO_SECRET_KEY: dirac
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 

#  minio2:
#   image: minio/minio
#   hostname: minio2
#   volumes:
#    - dirac_storage2:/export
#   ports:
#    - "9002:9000"
#   networks:
#    - dirac_distributed
#   environment:
#    MINIO_ACCESS_KEY: nlesc
#    MINIO_SECRET_KEY: dirac
#   deploy:
#    restart_policy:
#     delay: 10s
#     max_attempts: 10
#     window: 60s
#   command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 

#  minio3:
#   image: minio/minio
#   hostname: minio3
#   volumes:
#    - dirac_storage3:/export
#   ports:
#    - "9003:9000"
#   networks:
#    - dirac_distributed
#   environment:
#    MINIO_ACCESS_KEY: nlesc
#    MINIO_SECRET_KEY: dirac
#   deploy:
#    restart_policy:
#     delay: 10s
#     max_attempts: 10
#     window: 60s
#   command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 

#  minio4:
#   image: minio/minio
#   hostname: minio4
#   volumes:
#    - dirac_storage4:/export
#   ports:
#    - "9004:9000"
#   networks:
#    - dirac_distributed
#   environment:
#    MINIO_ACCESS_KEY: nlesc
#    MINIO_SECRET_KEY: dirac
#   deploy:
#    restart_policy:
#     delay: 10s
#     max_attempts: 10
#     window: 60s
#   command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 

volumes:
  dirac_storage1:
  # dirac_storage2:
  # dirac_storage3:
  # dirac_storage4:

# networks:
#  dirac_distributed:
#   driver: overlay
#   # external: true


networks:
  dirac_distributed:
    external: 
      name: dirac_distributed


# secrets:
#   secret_key:
#     external: true
#   access_key:
#     external: true