version: '3'

services:
 minio1:
  image: minio/minio
  hostname: minio1
  volumes:
   - dirac_storage1:/export
  ports:
   - "9001:9000"
  networks:
   - minio_distributed
  environment:
   MINIO_ACCESS_KEY: T615EUK8GNG353JSM3ZH
   MINIO_SECRET_KEY: uahJv4pzsRogtayBvPKUXVOLV1WScw7p4gfjsBtK
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 

 minio2:
  image: minio/minio
  hostname: minio2
  volumes:
   - dirac_storage2:/export
  ports:
   - "9002:9000"
  networks:
   - minio_distributed
  environment:
   MINIO_ACCESS_KEY: T615EUK8GNG353JSM3ZH
   MINIO_SECRET_KEY: uahJv4pzsRogtayBvPKUXVOLV1WScw7p4gfjsBtK
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 

 minio3:
  image: minio/minio
  hostname: minio3
  volumes:
   - dirac_storage3:/export
  ports:
   - "9003:9000"
  networks:
   - minio_distributed
  environment:
   MINIO_ACCESS_KEY: T615EUK8GNG353JSM3ZH
   MINIO_SECRET_KEY: uahJv4pzsRogtayBvPKUXVOLV1WScw7p4gfjsBtK
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 

 minio4:
  image: minio/minio
  hostname: minio4
  volumes:
   - dirac_storage4:/export
  ports:
   - "9004:9000"
  networks:
   - minio_distributed
  environment:
   MINIO_ACCESS_KEY: T615EUK8GNG353JSM3ZH
   MINIO_SECRET_KEY: uahJv4pzsRogtayBvPKUXVOLV1WScw7p4gfjsBtK
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 

volumes:
  dirac_storage1:
  dirac_storage2:
  dirac_storage3:
  dirac_storage4:

networks:
 minio_distributed:
  driver: overlay

# secrets:
#   secret_key:
#     external: true
#   access_key:
#     external: true