version: '3'
services:

  master:
    image: fdiblen/spark-master:latest
    hostname: sparkmaster
    networks:
      spark-net:
        aliases:
          - sparkmaster
          - spark-master
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 120s
    ports:
      - "8080:8080"
      - "7077:7077"
    env_file: 
      - ./cluster.env

  worker:
    image: fdiblen/spark-worker:latest
    #hostname: sparkworker
    hostname: sparkworker{{.Task.Slot}}
    depends_on:
      - master
    networks:
      spark-net:
        aliases:
          - sparkworker{{.Task.Slot}}
    environment:
      - SPARK_MASTER=spark://sparkmaster:7077
    deploy:
      replicas: 2
      mode: replicated
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 120s
    ports:
      - "8081:8081"
    env_file:
      - ./cluster.env

networks:
  spark-net:
    external: true
